### ISSUE TITLE
render_auto_save.py

### ISSUE THREAD

**Issue by mond-cz** [ICarryTheDustOfAJourney/Autosave-Render#1]
Sorry not an issue ... just if you know about **render_auto_save.py** addon bundled with any experimental build https://developer.blender.org/diffusion/BAC/browse/master/render_auto_save.py;10ebd1e553b16e599b51b8f1afcfee764365be26

**Comment by ICarryTheDustOfAJourney** [comment]
Thanks for reporting!

Might be hard to believe, but I haven't seen this. I checked V3Alpha for something similar, but didn't find anything. 
I had this idea on my mind for years, and now that I lost some work recently I decided to code it.

May be I came across this some day in the past (seems to exist since 2012) and forgot that.
Even similar naming. I re-invented the wheel, sort of.  

Can they co-exist? Have to find out.

**Comment by ICarryTheDustOfAJourney** [comment]
After a short test on V3.0 alpha:
- both addons seem to coexist peacefully
- haven't found any output from render_auto_save.py (using windows), may be I'm stupid
- they are covering not exactly the same topic, but very similar. My idea was to save a restoreable history of one's progress, what render_auto_save.py doesn't provide

...still flabbergasted 🙃

**Comment by ICarryTheDustOfAJourney** [comment]
I'll close that for now. If you think I should do something about it, feel invited to contact me again.

**Comment by mond-cz** [comment]
Thanks for reply ... save render automatically is one of my most used addon :) So I'm very interested :) 
For end user it is always better to find addon ready in build to use, than hunting updates over an internet. So I thought you could be interested to participate on the current (old) one than to split coderer's power.

It is working for me in 3.0 Alpha for Mac ... yes save before rendering (it make sense since default directory for "auto save" folder is next to the .blend file.

And yes it seems to be a bit abandoned :) So any enthusiast is welcomed :)
Thank you for your work anyway ... I'm going to check your version.

**Comment by ICarryTheDustOfAJourney** [comment]
Feedback welcome!

Are you the author of the old one? 
Which features of the old are you using? 
Might add some of those, now that I have the sources.

I still have some ideas, just released a new version, that allows simple comments to be saved in dirnames.
Might approach blender for an integration once the dust has setteled a bit and others find it useful too.
